services:
  fwa-monitor:
    build: .
    container_name: fwa-monitor
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./:/app
    ports:
      - "8088:8088"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8088"]
    restart: unless-stopped
